### ISSUE TITLE
Prompt for number

### ISSUE THREAD

**Issue by scottrigby** [farmotive/kex#6]
Is it ever really valuable to exec into the very first container listed in your namespace? Currently you have a 1/N chance with `kex`. Otherwise, you again type `kex -n <NUM> [OPTIONS]`. What if we instead make `kex` default to `--list`, and prompt for a number (it can still default to 1 if you hit enter with no number). Worst case you type one extra key… normal case, you save 8 keys (plus any addtl options). Thoughts?

**Comment by lypht** [comment]
I guess it depends on the use case.  In a new cluster or namespace, it's likely there would be only one pod on first pass.  In an established namespace, there likely would be n+1.  On the one hand, having the default match kubectx and kubens list rather than first pod would standardize; on the other, the longer it would take to switch, the more disruptive the change would be for active users.
