### ISSUE TITLE
namespace support

### ISSUE THREAD

**Issue by rimusz** [farmotive/kex#7]
flag `-n` would be nice if allowed to set the `namespace`

**Comment by lypht** [comment]
The `-n` flag is currently reserved to select the number of the pod.  We could use `-ns` and `--namespace` yet highly recommend checking out https://github.com/ahmetb/kubectx.  Ahmet's utility is the inspiration for kex, and stores the namespace in current context within `~/.kube`.  

It might make sense to use the `kex --namespace` flag in a manner similar to `pushd` and `popd`, where the switch is relevant to the current command, but does not otherwise alter the active context.

**Comment by rimusz** [comment]
`-n` it is usual `kubectl` flag, but `-ns` would do too

**Comment by scottrigby** [comment]
We could change [-n <NUMBER>] to [-p <POD>], and use -n for --namespace.

I was thinking though isn't this what kns is for?

**Comment by rimusz** [comment]
` [-n ] to [-p ], and use -n for --namespace.` 👍

**Comment by bookshelfdave** [comment]
support for `--all-namespaces` would be nice as well, but that might be trickier as you'd also need to parse out the namespace for the selected pod to exec into it.

**Comment by lypht** [comment]
Resolved with @metadave's work.  Thanks, Dave!
